#include "event_episode_service.h"
#include "stm32l4xx_hal.h"
#include <limits.h>
#include <string.h>
static bool Reached(uint32_t n,uint32_t d){return(int32_t)(n-d)>=0;}
static void Clear(event_episode_action_t*a){memset(a,0,sizeof(*a));a->temperature_source=EVENT_EPISODE_TEMP_SOURCE_NONE;}
static void Inc(uint16_t*v){if(*v<UINT16_MAX)(*v)++;}
static uint16_t U16(uint64_t v){return v>UINT16_MAX?UINT16_MAX:(uint16_t)v;}static uint32_t U32(uint64_t v){return v>UINT32_MAX?UINT32_MAX:(uint32_t)v;}
static bool Mpu(bolus_acquisition_level_t l,uint16_t p){switch(l){case BOLUS_ACQUISITION_LEVEL_0:return false;case BOLUS_ACQUISITION_LEVEL_1:return p==1U;case BOLUS_ACQUISITION_LEVEL_2:return p==1U||(p%4U)==0U;case BOLUS_ACQUISITION_LEVEL_3:return p==1U||(p%3U)==0U;case BOLUS_ACQUISITION_LEVEL_4:return p==1U||(p%2U)==0U;case BOLUS_ACQUISITION_LEVEL_5:return true;default:return false;}}
static void Summary(const event_episode_service_t*s,event_episode_summary_t*o){uint64_t m=0,q=0,v=0;memset(o,0,sizeof(*o));o->episode_sequence=s->active_sequence;o->start_time_ms=s->start_time_ms;o->last_pulse_time_ms=s->last_pulse_time_ms;o->close_deadline_ms=s->close_deadline_ms;o->active_span_ms=s->last_activity_time_ms-s->start_time_ms;o->source_flags=s->source_flags;o->thermal_active=s->thermal_active;o->pulse_count=s->pulse_count;o->suppressed_retrigger_count=s->suppressed_retrigger_count;o->inter_pulse_interval_count=s->inter_pulse_interval_count;if(s->inter_pulse_interval_count){m=s->inter_pulse_interval_sum_ms/s->inter_pulse_interval_count;q=s->inter_pulse_interval_sum_sq_ms2/s->inter_pulse_interval_count;v=q>=m*m?q-m*m:0;o->inter_pulse_interval_mean_ms=U32(m);o->inter_pulse_interval_variance_ms2=U32(v);}o->temperature_sample_count=s->temperature_sample_count;o->pulse_temperature_count=s->pulse_temperature_count;o->followup_temperature_count=s->followup_temperature_count;o->missed_followup_count=s->missed_followup_count;o->pulse_driven_temperature=s->pulse_driven_temperature;o->temperature_valid=s->temperature_valid;o->temperature_first_mdeg_c=s->temperature_first_mdeg_c;o->temperature_current_mdeg_c=s->temperature_current_mdeg_c;o->temperature_min_mdeg_c=s->temperature_min_mdeg_c;o->temperature_max_mdeg_c=s->temperature_max_mdeg_c;o->max_negative_excursion_mdeg_c=s->max_negative_excursion_mdeg_c;o->mpu_burst_count=s->mpu_burst_count;o->mpu_skipped_by_policy_count=s->mpu_skipped_by_policy_count;o->mpu_failure_count=s->mpu_failure_count;o->mpu_sample_count=s->mpu_sample_count;o->mpu_peak_dynamic_accel_mg=s->mpu_peak_dynamic_accel_mg;o->mpu_peak_angular_velocity_dps=s->mpu_peak_angular_velocity_dps;o->mpu_total_angular_motion_cdeg=U32(s->mpu_total_angular_motion_cdeg);o->mpu_orientation_valid_count=s->mpu_orientation_valid_count;o->mpu_max_orientation_change_cdeg=s->mpu_max_orientation_change_cdeg;if(s->mpu_burst_count){o->mpu_mean_rms_dynamic_accel_mg=U16(s->mpu_rms_dynamic_accel_sum_mg/s->mpu_burst_count);o->mpu_mean_rms_angular_velocity_dps=U16(s->mpu_rms_angular_velocity_sum_dps/s->mpu_burst_count);}}
static void Reset(event_episode_service_t*s){uint32_t seq=s->sequence_counter;bolus_acquisition_level_t l=s->acquisition_level;uint32_t q=s->quiet_timeout_ms,g=s->retrigger_guard_ms,m=s->max_duration_ms,fo[4];memcpy(fo,s->temp_followup_offset_ms,sizeof(fo));bool init=s->initialized,eventValid=s->last_closed_summary_valid;event_episode_summary_t last=s->last_closed_summary;memset(s,0,sizeof(*s));s->sequence_counter=seq;s->acquisition_level=l;s->quiet_timeout_ms=q;s->retrigger_guard_ms=g;s->max_duration_ms=m;memcpy(s->temp_followup_offset_ms,fo,sizeof(fo));s->initialized=init;s->last_closed_summary_valid=eventValid;s->last_closed_summary=last;}
static void Close(event_episode_service_t*s){Summary(s,&s->last_closed_summary);s->last_closed_summary_valid=true;Reset(s);}
static void Start(event_episode_service_t*s,uint32_t n,uint8_t f,bool mot){s->sequence_counter=s->sequence_counter<UINT32_MAX?s->sequence_counter+1U:1U;s->active=true;s->active_sequence=s->sequence_counter;s->start_time_ms=n;s->last_activity_time_ms=n;s->last_pulse_time_ms=mot?n:0U;s->close_deadline_ms=n+s->quiet_timeout_ms;s->max_deadline_ms=n+s->max_duration_ms;s->source_flags=f;s->thermal_active=(f&(EVENT_EPISODE_SOURCE_TEMP_HIGH|EVENT_EPISODE_SOURCE_TEMP_LOW))!=0U;if(mot){s->pulse_count=1U;s->followup_active=true;s->next_followup_due_ms=n+s->temp_followup_offset_ms[0];}}
event_episode_status_t EventEpisodeService_Init(event_episode_service_t*s,const bolus_runtime_config_t*c){uint32_t seq;if(!s||!c)return EVENT_EPISODE_ERROR_PARAM;if(!BolusRuntimeConfig_Validate(c))return EVENT_EPISODE_ERROR_CONFIG;seq=s->sequence_counter;memset(s,0,sizeof(*s));s->sequence_counter=seq;s->acquisition_level=c->acquisition_level;s->quiet_timeout_ms=(uint32_t)c->event_processing.episode_quiet_timeout_s*1000UL;s->retrigger_guard_ms=c->event_processing.episode_retrigger_guard_ms;s->max_duration_ms=(uint32_t)c->event_processing.episode_max_duration_s*1000UL;s->temp_followup_offset_ms[0]=(uint32_t)c->event_processing.episode_temp_followup_1_s*1000UL;s->temp_followup_offset_ms[1]=(uint32_t)c->event_processing.episode_temp_followup_2_s*1000UL;s->temp_followup_offset_ms[2]=(uint32_t)c->event_processing.episode_temp_followup_3_s*1000UL;s->temp_followup_offset_ms[3]=(uint32_t)c->event_processing.episode_temp_followup_4_s*1000UL;s->initialized=true;return EVENT_EPISODE_OK;}
event_episode_status_t EventEpisodeService_OnMotionPulse(event_episode_service_t*s,uint32_t n,event_episode_action_t*a){uint32_t dt=0;bool take;if(!s||!a)return EVENT_EPISODE_ERROR_PARAM;Clear(a);if(!s->initialized)return EVENT_EPISODE_ERROR_NOT_INITIALIZED;if(s->active&&(Reached(n,s->max_deadline_ms)||(!s->thermal_active&&Reached(n,s->close_deadline_ms)))){Close(s);a->episode_closed=true;}if(!s->active){Start(s,n,EVENT_EPISODE_SOURCE_MOTION,true);a->episode_started=true;a->pulse_accepted=true;a->take_temperature_now=true;a->temperature_source=EVENT_EPISODE_TEMP_SOURCE_FIRST_PULSE;}else{if(s->last_pulse_time_ms)dt=n-s->last_pulse_time_ms;if(s->last_pulse_time_ms&&s->retrigger_guard_ms&&dt<s->retrigger_guard_ms){Inc(&s->suppressed_retrigger_count);a->pulse_suppressed_by_guard=true;a->episode_sequence=s->active_sequence;a->pulse_count=s->pulse_count;a->source_flags=s->source_flags;return EVENT_EPISODE_OK;}a->pulse_accepted=true;if(s->last_pulse_time_ms){a->inter_pulse_interval_valid=true;a->inter_pulse_interval_ms=dt;Inc(&s->inter_pulse_interval_count);s->inter_pulse_interval_sum_ms+=dt;s->inter_pulse_interval_sum_sq_ms2+=(uint64_t)dt*dt;}s->last_pulse_time_ms=n;s->last_activity_time_ms=n;s->close_deadline_ms=n+s->quiet_timeout_ms;s->source_flags|=EVENT_EPISODE_SOURCE_MOTION;Inc(&s->pulse_count);if(s->acquisition_level>=BOLUS_ACQUISITION_LEVEL_4){a->take_temperature_now=true;a->temperature_source=EVENT_EPISODE_TEMP_SOURCE_MOTION_PULSE;s->pulse_driven_temperature=true;}}take=Mpu(s->acquisition_level,s->pulse_count);a->take_mpu_burst_now=take;if(!take){a->mpu_skipped_by_policy=true;Inc(&s->mpu_skipped_by_policy_count);}a->episode_sequence=s->active_sequence;a->pulse_count=s->pulse_count;a->source_flags=s->source_flags;return EVENT_EPISODE_OK;}
event_episode_status_t EventEpisodeService_OnThermalAlert(event_episode_service_t*s,uint32_t n,bool hi,bool lo,event_episode_action_t*a){uint8_t f=0;if(!s||!a||(!hi&&!lo))return EVENT_EPISODE_ERROR_PARAM;Clear(a);if(!s->initialized)return EVENT_EPISODE_ERROR_NOT_INITIALIZED;if(hi)f|=EVENT_EPISODE_SOURCE_TEMP_HIGH;if(lo)f|=EVENT_EPISODE_SOURCE_TEMP_LOW;if(s->active&&Reached(n,s->max_deadline_ms)){Close(s);a->episode_closed=true;}if(!s->active){Start(s,n,f,false);a->episode_started=true;}else{s->source_flags|=f;s->thermal_active=true;s->last_activity_time_ms=n;}a->episode_sequence=s->active_sequence;a->pulse_count=s->pulse_count;a->source_flags=s->source_flags;return EVENT_EPISODE_OK;}
event_episode_status_t EventEpisodeService_OnThermalNormal(event_episode_service_t*s,uint32_t n,event_episode_action_t*a){if(!s||!a)return EVENT_EPISODE_ERROR_PARAM;Clear(a);if(!s->initialized)return EVENT_EPISODE_ERROR_NOT_INITIALIZED;if(!s->active)return EVENT_EPISODE_OK;s->thermal_active=false;s->last_activity_time_ms=n;if(!s->pulse_count||Reached(n,s->close_deadline_ms)){a->episode_sequence=s->active_sequence;a->pulse_count=s->pulse_count;a->source_flags=s->source_flags;a->episode_closed=true;Close(s);}return EVENT_EPISODE_OK;}
event_episode_status_t EventEpisodeService_Poll(event_episode_service_t*s,uint32_t n,event_episode_action_t*a){uint8_t i;if(!s||!a)return EVENT_EPISODE_ERROR_PARAM;Clear(a);if(!s->initialized)return EVENT_EPISODE_ERROR_NOT_INITIALIZED;if(!s->active)return EVENT_EPISODE_OK;if(Reached(n,s->max_deadline_ms)||(!s->thermal_active&&Reached(n,s->close_deadline_ms))){a->episode_sequence=s->active_sequence;a->pulse_count=s->pulse_count;a->source_flags=s->source_flags;a->episode_closed=true;Close(s);return EVENT_EPISODE_OK;}if(s->followup_active&&Reached(n,s->next_followup_due_ms)){a->take_temperature_now=true;a->temperature_source=EVENT_EPISODE_TEMP_SOURCE_FOLLOWUP;a->episode_sequence=s->active_sequence;a->pulse_count=s->pulse_count;a->source_flags=s->source_flags;i=(uint8_t)(s->next_followup_index+1U);while(i<EVENT_EPISODE_TEMP_FOLLOWUP_COUNT&&Reached(n,s->start_time_ms+s->temp_followup_offset_ms[i])){Inc(&s->missed_followup_count);i++;}if(i>=EVENT_EPISODE_TEMP_FOLLOWUP_COUNT){s->followup_active=false;s->next_followup_index=i;s->next_followup_due_ms=0U;}else{s->next_followup_index=i;s->next_followup_due_ms=s->start_time_ms+s->temp_followup_offset_ms[i];}}return EVENT_EPISODE_OK;}
event_episode_status_t EventEpisodeService_RecordTemperature(event_episode_service_t*s,event_episode_temperature_source_t src,int32_t t){int32_t ex;if(!s||!s->initialized||!s->active||src==EVENT_EPISODE_TEMP_SOURCE_NONE)return EVENT_EPISODE_ERROR_PARAM;if(!s->temperature_valid){s->temperature_valid=true;s->temperature_first_mdeg_c=t;s->temperature_current_mdeg_c=t;s->temperature_min_mdeg_c=t;s->temperature_max_mdeg_c=t;}else{ex=t-s->temperature_max_mdeg_c;if(ex<s->max_negative_excursion_mdeg_c)s->max_negative_excursion_mdeg_c=ex;if(t<s->temperature_min_mdeg_c)s->temperature_min_mdeg_c=t;if(t>s->temperature_max_mdeg_c)s->temperature_max_mdeg_c=t;s->temperature_current_mdeg_c=t;}s->last_activity_time_ms=HAL_GetTick();Inc(&s->temperature_sample_count);if(src==EVENT_EPISODE_TEMP_SOURCE_FIRST_PULSE||src==EVENT_EPISODE_TEMP_SOURCE_MOTION_PULSE)Inc(&s->pulse_temperature_count);else if(src==EVENT_EPISODE_TEMP_SOURCE_FOLLOWUP)Inc(&s->followup_temperature_count);return EVENT_EPISODE_OK;}
event_episode_status_t EventEpisodeService_RecordMpuBurst(event_episode_service_t*s,const event_episode_mpu_features_t*f){if(!s||!f||!s->initialized||!s->active||!f->sample_count)return EVENT_EPISODE_ERROR_PARAM;Inc(&s->mpu_burst_count);s->mpu_sample_count=(UINT32_MAX-s->mpu_sample_count<f->sample_count)?UINT32_MAX:s->mpu_sample_count+f->sample_count;if(f->peak_dynamic_accel_mg>s->mpu_peak_dynamic_accel_mg)s->mpu_peak_dynamic_accel_mg=f->peak_dynamic_accel_mg;s->mpu_rms_dynamic_accel_sum_mg+=f->rms_dynamic_accel_mg;if(f->peak_angular_velocity_dps>s->mpu_peak_angular_velocity_dps)s->mpu_peak_angular_velocity_dps=f->peak_angular_velocity_dps;s->mpu_rms_angular_velocity_sum_dps+=f->rms_angular_velocity_dps;s->mpu_total_angular_motion_cdeg+=f->total_angular_motion_cdeg;if(f->orientation_change_valid){Inc(&s->mpu_orientation_valid_count);if(f->orientation_change_cdeg>s->mpu_max_orientation_change_cdeg)s->mpu_max_orientation_change_cdeg=f->orientation_change_cdeg;}s->last_activity_time_ms=HAL_GetTick();return EVENT_EPISODE_OK;}
void EventEpisodeService_MarkMpuFailure(event_episode_service_t*s){if(s&&s->initialized&&s->active)Inc(&s->mpu_failure_count);}
bool EventEpisodeService_IsActive(const event_episode_service_t*s){return s&&s->initialized&&s->active;}
event_episode_status_t EventEpisodeService_GetActiveSummary(const event_episode_service_t*s,event_episode_summary_t*o){if(!s||!o)return EVENT_EPISODE_ERROR_PARAM;if(!s->initialized)return EVENT_EPISODE_ERROR_NOT_INITIALIZED;if(!s->active)return EVENT_EPISODE_ERROR_PARAM;Summary(s,o);return EVENT_EPISODE_OK;}
event_episode_status_t EventEpisodeService_GetLastClosedSummary(const event_episode_service_t*s,event_episode_summary_t*o){if(!s||!o)return EVENT_EPISODE_ERROR_PARAM;if(!s->initialized)return EVENT_EPISODE_ERROR_NOT_INITIALIZED;if(!s->last_closed_summary_valid)return EVENT_EPISODE_ERROR_PARAM;*o=s->last_closed_summary;return EVENT_EPISODE_OK;}
