#include "event_digest_service.h"
#include <limits.h>
#include <string.h>
static uint8_t U8(uint32_t v){return v>UINT8_MAX?UINT8_MAX:(uint8_t)v;}
static uint16_t U16(uint32_t v){return v>UINT16_MAX?UINT16_MAX:(uint16_t)v;}
static int16_t Cc(int32_t m){int32_t v=m>=0?(m+5)/10:(m-5)/10;if(v>INT16_MAX)v=INT16_MAX;if(v<INT16_MIN)v=INT16_MIN;return(int16_t)v;}
void EventDigestService_Init(event_digest_service_t*s){if(s)memset(s,0,sizeof(*s));}
bool EventDigestService_PushClosedEpisode(event_digest_service_t*s,const event_episode_summary_t*e,uint32_t ws){bolus_event_digest_t*d;uint32_t off;if(!s||!e)return false;if(s->count>=EVENT_DIGEST_CAPACITY){s->overflow_count++;s->overflow_latched=true;return false;}d=&s->items[s->count];memset(d,0,sizeof(*d));if((int32_t)(e->start_time_ms-ws)<0){d->flags|=BOLUS_EVENT_DIGEST_FLAG_CARRY;}else{off=e->start_time_ms-ws;d->start_offset_s=U16((off+500U)/1000U);}d->duration_s=U16((e->active_span_ms+500U)/1000U);d->pulse_count=U8(e->pulse_count);d->mean_inter_pulse_interval_s=U8((e->inter_pulse_interval_mean_ms+500U)/1000U);if(e->temperature_valid){d->temperature_delta_centi_c=Cc(e->temperature_current_mdeg_c-e->temperature_first_mdeg_c);d->flags|=BOLUS_EVENT_DIGEST_FLAG_TEMP_VALID;}d->rms_dynamic_accel_mg=e->mpu_mean_rms_dynamic_accel_mg;d->peak_dynamic_accel_mg=e->mpu_peak_dynamic_accel_mg;d->peak_angular_velocity_dps=e->mpu_peak_angular_velocity_dps;d->orientation_change_cdeg=e->mpu_max_orientation_change_cdeg;if(e->source_flags&EVENT_EPISODE_SOURCE_MOTION)d->flags|=BOLUS_EVENT_DIGEST_FLAG_MOTION;if(e->source_flags&EVENT_EPISODE_SOURCE_TEMP_HIGH)d->flags|=BOLUS_EVENT_DIGEST_FLAG_TEMP_HIGH;if(e->source_flags&EVENT_EPISODE_SOURCE_TEMP_LOW)d->flags|=BOLUS_EVENT_DIGEST_FLAG_TEMP_LOW;if(e->mpu_burst_count)d->flags|=BOLUS_EVENT_DIGEST_FLAG_MPU_USED;if(e->mpu_skipped_by_policy_count)d->flags|=BOLUS_EVENT_DIGEST_FLAG_MPU_SKIPPED;if(e->mpu_failure_count)d->flags|=BOLUS_EVENT_DIGEST_FLAG_MPU_FAILED;s->count++;s->pushed_count++;return true;}
uint8_t EventDigestService_SnapshotAndClear(event_digest_service_t*s,bolus_event_digest_t*d,uint8_t cap){uint8_t n;if(!s||!d||!cap)return 0U;n=s->count<cap?s->count:cap;memcpy(d,s->items,(size_t)n*sizeof(*d));if(n<s->count){s->overflow_count+=(uint32_t)(s->count-n);s->overflow_latched=true;}memset(s->items,0,sizeof(s->items));s->count=0U;return n;}
bool EventDigestService_ConsumeOverflow(event_digest_service_t*s){bool v;if(!s)return false;v=s->overflow_latched;s->overflow_latched=false;return v;}
