#ifndef EVENT_EPISODE_SERVICE_H
#define EVENT_EPISODE_SERVICE_H
#include <stdbool.h>
#include <stdint.h>
#include "../Config/bolus_runtime_config.h"
#define EVENT_EPISODE_TEMP_FOLLOWUP_COUNT 4U
#define EVENT_EPISODE_SOURCE_MOTION (1U<<0)
#define EVENT_EPISODE_SOURCE_TEMP_HIGH (1U<<1)
#define EVENT_EPISODE_SOURCE_TEMP_LOW (1U<<2)
typedef enum{EVENT_EPISODE_OK=0,EVENT_EPISODE_ERROR_PARAM,EVENT_EPISODE_ERROR_CONFIG,EVENT_EPISODE_ERROR_NOT_INITIALIZED}event_episode_status_t;
typedef enum{EVENT_EPISODE_TEMP_SOURCE_NONE=0,EVENT_EPISODE_TEMP_SOURCE_FIRST_PULSE,EVENT_EPISODE_TEMP_SOURCE_FOLLOWUP,EVENT_EPISODE_TEMP_SOURCE_MOTION_PULSE,EVENT_EPISODE_TEMP_SOURCE_THERMAL}event_episode_temperature_source_t;
typedef struct{uint16_t sample_count,peak_dynamic_accel_mg,rms_dynamic_accel_mg,peak_angular_velocity_dps,rms_angular_velocity_dps;uint32_t total_angular_motion_cdeg;bool orientation_change_valid;uint16_t orientation_change_cdeg;}event_episode_mpu_features_t;
typedef struct{bool pulse_accepted,pulse_suppressed_by_guard,episode_started,episode_closed,followup_schedule_cancelled,take_temperature_now,take_mpu_burst_now,mpu_skipped_by_policy,inter_pulse_interval_valid;event_episode_temperature_source_t temperature_source;uint32_t inter_pulse_interval_ms,episode_sequence;uint8_t source_flags;uint16_t pulse_count;}event_episode_action_t;
typedef struct{uint32_t episode_sequence,start_time_ms,last_pulse_time_ms,close_deadline_ms,active_span_ms;uint8_t source_flags;bool thermal_active;uint16_t pulse_count,suppressed_retrigger_count,inter_pulse_interval_count;uint32_t inter_pulse_interval_mean_ms,inter_pulse_interval_variance_ms2;uint16_t temperature_sample_count,pulse_temperature_count,followup_temperature_count,missed_followup_count;bool pulse_driven_temperature,temperature_valid;int32_t temperature_first_mdeg_c,temperature_current_mdeg_c,temperature_min_mdeg_c,temperature_max_mdeg_c,max_negative_excursion_mdeg_c;uint16_t mpu_burst_count,mpu_skipped_by_policy_count,mpu_failure_count;uint32_t mpu_sample_count;uint16_t mpu_peak_dynamic_accel_mg,mpu_mean_rms_dynamic_accel_mg,mpu_peak_angular_velocity_dps,mpu_mean_rms_angular_velocity_dps;uint32_t mpu_total_angular_motion_cdeg;uint16_t mpu_orientation_valid_count,mpu_max_orientation_change_cdeg;}event_episode_summary_t;
typedef struct{bool initialized,active,thermal_active;bolus_acquisition_level_t acquisition_level;uint32_t quiet_timeout_ms,retrigger_guard_ms,max_duration_ms,temp_followup_offset_ms[4],sequence_counter,active_sequence,start_time_ms,last_activity_time_ms,last_pulse_time_ms,close_deadline_ms,max_deadline_ms;uint8_t source_flags;uint16_t pulse_count,suppressed_retrigger_count,inter_pulse_interval_count;uint64_t inter_pulse_interval_sum_ms,inter_pulse_interval_sum_sq_ms2;bool followup_active;uint8_t next_followup_index;uint32_t next_followup_due_ms;bool pulse_driven_temperature;uint16_t temperature_sample_count,pulse_temperature_count,followup_temperature_count,missed_followup_count;bool temperature_valid;int32_t temperature_first_mdeg_c,temperature_current_mdeg_c,temperature_min_mdeg_c,temperature_max_mdeg_c,max_negative_excursion_mdeg_c;uint16_t mpu_burst_count,mpu_skipped_by_policy_count,mpu_failure_count;uint32_t mpu_sample_count;uint16_t mpu_peak_dynamic_accel_mg;uint64_t mpu_rms_dynamic_accel_sum_mg;uint16_t mpu_peak_angular_velocity_dps;uint64_t mpu_rms_angular_velocity_sum_dps,mpu_total_angular_motion_cdeg;uint16_t mpu_orientation_valid_count,mpu_max_orientation_change_cdeg;bool last_closed_summary_valid;event_episode_summary_t last_closed_summary;}event_episode_service_t;
event_episode_status_t EventEpisodeService_Init(event_episode_service_t*,const bolus_runtime_config_t*);
event_episode_status_t EventEpisodeService_OnMotionPulse(event_episode_service_t*,uint32_t,event_episode_action_t*);
event_episode_status_t EventEpisodeService_OnThermalAlert(event_episode_service_t*,uint32_t,bool,bool,event_episode_action_t*);
event_episode_status_t EventEpisodeService_OnThermalNormal(event_episode_service_t*,uint32_t,event_episode_action_t*);
event_episode_status_t EventEpisodeService_Poll(event_episode_service_t*,uint32_t,event_episode_action_t*);
event_episode_status_t EventEpisodeService_RecordTemperature(event_episode_service_t*,event_episode_temperature_source_t,int32_t);
event_episode_status_t EventEpisodeService_RecordMpuBurst(event_episode_service_t*,const event_episode_mpu_features_t*);
void EventEpisodeService_MarkMpuFailure(event_episode_service_t*);
bool EventEpisodeService_IsActive(const event_episode_service_t*);
event_episode_status_t EventEpisodeService_GetActiveSummary(const event_episode_service_t*,event_episode_summary_t*);
event_episode_status_t EventEpisodeService_GetLastClosedSummary(const event_episode_service_t*,event_episode_summary_t*);
#endif
