#include "lorawan_uplink_service.h"

#include "bolus_lorawan_credentials.h"
#include "downlink_management_service.h"
#include "fault_manager.h"
#include "main.h"
#include "rfm95w_board.h"

#include <stddef.h>
#include <string.h>

/*
 * ============================================================
 * [UNTESTED] LoRaWAN ABP uplink + downlink integration staging
 * ============================================================
 * The I-CUBE-LRWAN stack in this repository is configured for EU868,
 * Class A and LoRaWAN 1.0.3 crypto. No OTAA join request is issued here.
 * Gateway/TTN validation is still required after this change.
 *
 * Downlink command acceptance must not be interpreted as live hardware apply;
 * see downlink_management_diag.pending_apply_mask.
 */

#define LORAWAN_UPLINK_BUSY_RETRY_MS       100UL
#define LORAWAN_ABP_LRWAN_VERSION_V103     0x01000300UL

typedef struct
{
    bool valid;
    uint8_t size;
    uint8_t attempts;
    uint16_t sequence;
    uint8_t payload[BOLUS_LORAWAN_MAX_APP_PAYLOAD];
} lorawan_uplink_queue_entry_t;

typedef enum
{
    LORAWAN_TX_KIND_NONE = 0,
    LORAWAN_TX_KIND_TELEMETRY,
    LORAWAN_TX_KIND_CONTROL_RESPONSE
} lorawan_tx_kind_t;

static lorawan_uplink_queue_entry_t s_queue[BOLUS_LORAWAN_QUEUE_DEPTH];
static uint8_t s_queue_head = 0U;
static uint8_t s_queue_tail = 0U;
static uint8_t s_queue_count = 0U;

/*
 * One dedicated priority slot for ACK/NACK generated by a received downlink.
 * It is intentionally separate from the telemetry queue so an RX1/RX2 command
 * response cannot corrupt or pop the telemetry head currently awaiting MCPS
 * confirmation.
 */
static bool s_control_response_pending = false;
static uint8_t s_control_response_size = 0U;
static uint8_t s_control_response_attempts = 0U;
static uint8_t s_control_response[DOWNLINK_MANAGEMENT_RESPONSE_SIZE] = {0};

static bool s_initialized = false;
static bool s_joined = false;
static bool s_tx_in_flight = false;
static lorawan_tx_kind_t s_tx_kind = LORAWAN_TX_KIND_NONE;
static uint32_t s_next_action_tick_ms = 0U;
static uint32_t s_retry_delay_ms = 2000U;
static uint8_t s_max_tx_attempts = 3U;

static uint8_t s_f_nwk_s_int_key[16] = BOLUS_LORAWAN_F_NWK_S_INT_KEY_BYTES;
static uint8_t s_s_nwk_s_int_key[16] = BOLUS_LORAWAN_S_NWK_S_INT_KEY_BYTES;
static uint8_t s_app_s_key[16] = BOLUS_LORAWAN_APP_S_KEY_BYTES;

/*
 * LoRaMacInitialization stores these pointers in MacCtx and uses them later
 * from TxDone/RxDone and MCPS/MLME processing. They therefore must have static
 * lifetime; stack-local instances become invalid as soon as Init returns and
 * can turn a later TxDone callback into a HardFault.
 */
static LoRaMacPrimitives_t s_mac_primitives;
static LoRaMacCallback_t s_mac_callbacks;

lorawan_uplink_diag_t lorawan_uplink_service_diag = {0};

static bool TimeReached(uint32_t now_ms, uint32_t deadline_ms)
{
    return ((int32_t)(now_ms - deadline_ms) >= 0);
}

static lorawan_uplink_queue_entry_t *QueueHead(void)
{
    if (s_queue_count == 0U)
    {
        return NULL;
    }

    return &s_queue[s_queue_head];
}

static void QueuePop(void)
{
    if (s_queue_count == 0U)
    {
        return;
    }

    memset(&s_queue[s_queue_head], 0, sizeof(s_queue[s_queue_head]));
    s_queue_head = (uint8_t)((s_queue_head + 1U) % BOLUS_LORAWAN_QUEUE_DEPTH);
    s_queue_count--;
    lorawan_uplink_service_diag.queue_count = s_queue_count;
}

static uint8_t MacGetBatteryLevel(void)
{
    return BAT_LEVEL_NO_MEASURE;
}

static uint16_t MacGetTemperatureLevel(void)
{
    return 0U;
}

static void MacGetUniqueId(uint8_t *id)
{
    uint32_t uid0;
    uint32_t uid1;
    uint32_t uid2;

    if (id == NULL)
    {
        return;
    }

    uid0 = HAL_GetUIDw0();
    uid1 = HAL_GetUIDw1();
    uid2 = HAL_GetUIDw2();

    id[0] = (uint8_t)(uid2 >> 24);
    id[1] = (uint8_t)(uid2 >> 16);
    id[2] = (uint8_t)(uid2 >> 8);
    id[3] = (uint8_t)uid2;
    uid0 ^= uid1;
    id[4] = (uint8_t)(uid0 >> 24);
    id[5] = (uint8_t)(uid0 >> 16);
    id[6] = (uint8_t)(uid0 >> 8);
    id[7] = (uint8_t)uid0;
}

static void MacNvmDataChange(uint16_t notify_flags)
{
    (void)notify_flags;
    lorawan_uplink_service_diag.nvm_change_count++;
}

static void MacProcessNotify(void)
{
    lorawan_uplink_service_diag.mac_process_pending = true;
}

static void MarkAbpSessionLost(uint32_t now_ms)
{
    s_joined = false;
    lorawan_uplink_service_diag.joined = false;
    lorawan_uplink_service_diag.abp_session_configured = false;
    lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_ERROR;
    s_next_action_tick_ms = now_ms;
    lorawan_uplink_service_diag.next_action_tick_ms = now_ms;
    FaultManager_Raise(BOLUS_FAULT_RF_COMM);
}

static void HandleControlResponseConfirm(McpsConfirm_t *confirm)
{
    if (confirm->Status == LORAMAC_EVENT_INFO_STATUS_OK)
    {
        lorawan_uplink_service_diag.downlink_response_tx_success_count++;
        s_control_response_pending = false;
        s_control_response_size = 0U;
        s_control_response_attempts = 0U;
        memset(s_control_response, 0, sizeof(s_control_response));
        (void)FaultManager_ClearFault(BOLUS_FAULT_RF_TX_TIMEOUT);
        s_next_action_tick_ms = HAL_GetTick();
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_JOINED_IDLE;
        return;
    }

    lorawan_uplink_service_diag.downlink_response_tx_failure_count++;

    if (s_control_response_attempts < s_max_tx_attempts)
    {
        s_next_action_tick_ms = HAL_GetTick() + s_retry_delay_ms;
        lorawan_uplink_service_diag.next_action_tick_ms = s_next_action_tick_ms;
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_RETRY_WAIT;
    }
    else
    {
        lorawan_uplink_service_diag.downlink_response_drop_count++;
        s_control_response_pending = false;
        s_control_response_size = 0U;
        s_control_response_attempts = 0U;
        memset(s_control_response, 0, sizeof(s_control_response));
        FaultManager_Raise(BOLUS_FAULT_RF_TX_TIMEOUT);
        s_next_action_tick_ms = HAL_GetTick();
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_JOINED_IDLE;
    }
}

static void MacMcpsConfirm(McpsConfirm_t *confirm)
{
    lorawan_uplink_queue_entry_t *entry;
    lorawan_tx_kind_t completed_kind;

    if (confirm == NULL)
    {
        return;
    }

    completed_kind = s_tx_kind;
    s_tx_kind = LORAWAN_TX_KIND_NONE;
    s_tx_in_flight = false;
    lorawan_uplink_service_diag.tx_in_flight = false;
    lorawan_uplink_service_diag.last_mcps_confirm_status = confirm->Status;
    lorawan_uplink_service_diag.last_uplink_counter = confirm->UpLinkCounter;
    lorawan_uplink_service_diag.last_tx_air_time_ms = confirm->TxTimeOnAir;

    if (completed_kind == LORAWAN_TX_KIND_CONTROL_RESPONSE)
    {
        HandleControlResponseConfirm(confirm);
        return;
    }

    entry = QueueHead();
    if (entry == NULL)
    {
        lorawan_uplink_service_diag.state =
            s_joined ? LORAWAN_UPLINK_STATE_JOINED_IDLE : LORAWAN_UPLINK_STATE_ERROR;
        return;
    }

    if (confirm->Status == LORAMAC_EVENT_INFO_STATUS_OK)
    {
        lorawan_uplink_service_diag.tx_success_count++;
        lorawan_uplink_service_diag.last_sequence_completed = entry->sequence;
        QueuePop();
        (void)FaultManager_ClearFault(BOLUS_FAULT_RF_TX_TIMEOUT);
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_JOINED_IDLE;
        s_next_action_tick_ms = HAL_GetTick();
    }
    else
    {
        lorawan_uplink_service_diag.tx_failure_count++;

        if (entry->attempts < s_max_tx_attempts)
        {
            lorawan_uplink_service_diag.tx_retry_count++;
            s_next_action_tick_ms = HAL_GetTick() + s_retry_delay_ms;
            lorawan_uplink_service_diag.next_action_tick_ms = s_next_action_tick_ms;
            lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_RETRY_WAIT;
        }
        else
        {
            lorawan_uplink_service_diag.tx_drop_count++;
            FaultManager_Raise(BOLUS_FAULT_RF_TX_TIMEOUT);
            QueuePop();
            s_next_action_tick_ms = HAL_GetTick();
            lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_JOINED_IDLE;
        }
    }
}

static void MacMcpsIndication(McpsIndication_t *indication, LoRaMacRxStatus_t *rx_status)
{
    uint8_t response[DOWNLINK_MANAGEMENT_RESPONSE_SIZE] = {0};
    uint8_t response_size = 0U;

    if (indication == NULL)
    {
        return;
    }

    if ((indication->Status != LORAMAC_EVENT_INFO_STATUS_OK) ||
        !indication->RxData)
    {
        return;
    }

    lorawan_uplink_service_diag.downlink_count++;
    lorawan_uplink_service_diag.last_downlink_counter = indication->DownLinkCounter;
    lorawan_uplink_service_diag.last_downlink_port = indication->Port;
    lorawan_uplink_service_diag.last_downlink_size = indication->BufferSize;

    if (rx_status != NULL)
    {
        lorawan_uplink_service_diag.last_downlink_rssi_dbm = rx_status->Rssi;
        lorawan_uplink_service_diag.last_downlink_snr_db = rx_status->Snr;
        lorawan_uplink_service_diag.last_downlink_slot = rx_status->RxSlot;
    }

    if (indication->Port != BOLUS_LORAWAN_DOWNLINK_PORT)
    {
        lorawan_uplink_service_diag.downlink_wrong_port_count++;
        return;
    }

    if (s_control_response_pending)
    {
        lorawan_uplink_service_diag.downlink_response_drop_count++;
        return;
    }

    lorawan_uplink_service_diag.downlink_command_count++;

    (void)DownlinkManagementService_HandleFrame(
        indication->Buffer,
        indication->BufferSize,
        response,
        sizeof(response),
        &response_size);

    if (response_size == 0U)
    {
        return;
    }

    memcpy(s_control_response, response, response_size);
    s_control_response_size = response_size;
    s_control_response_attempts = 0U;
    s_control_response_pending = true;
    lorawan_uplink_service_diag.downlink_response_queued_count++;
}

static void MacMlmeConfirm(MlmeConfirm_t *confirm)
{
    /*
     * ABP does not issue MLME_JOIN. Keep a valid callback because LoRaMAC
     * requires all primitive callbacks to be installed.
     */
    (void)confirm;
}

static void MacMlmeIndication(MlmeIndication_t *indication, LoRaMacRxStatus_t *rx_status)
{
    (void)indication;
    (void)rx_status;
}

static LoRaMacStatus_t SetMib(Mib_t type, MibParam_t param)
{
    MibRequestConfirm_t request;

    memset(&request, 0, sizeof(request));
    request.Type = type;
    request.Param = param;
    return LoRaMacMibSetRequestConfirm(&request);
}

static bool ConfigureMacPolicy(void)
{
    MibRequestConfirm_t current_class;
    MibParam_t param;
    LoRaMacStatus_t status;

    /*
     * LoRaMac 4.4.7 returns PARAMETER_INVALID when MIB_DEVICE_CLASS is set to
     * CLASS_A while the current class is already CLASS_A. Query first and only
     * request a class transition when one is actually required.
     */
    memset(&current_class, 0, sizeof(current_class));
    current_class.Type = MIB_DEVICE_CLASS;
    status = LoRaMacMibGetRequestConfirm(&current_class);
    if (status != LORAMAC_STATUS_OK)
    {
        lorawan_uplink_service_diag.last_mac_status = status;
        return false;
    }

    if (current_class.Param.Class != CLASS_A)
    {
        memset(&param, 0, sizeof(param));
        param.Class = CLASS_A;
        status = SetMib(MIB_DEVICE_CLASS, param);
        if (status != LORAMAC_STATUS_OK)
        {
            lorawan_uplink_service_diag.last_mac_status = status;
            return false;
        }
    }

    memset(&param, 0, sizeof(param));
    param.AdrEnable = (BOLUS_LORAWAN_ADR_ENABLE != 0);
    status = SetMib(MIB_ADR, param);
    if (status != LORAMAC_STATUS_OK)
    {
        lorawan_uplink_service_diag.last_mac_status = status;
        return false;
    }

    memset(&param, 0, sizeof(param));
    param.EnablePublicNetwork = true;
    status = SetMib(MIB_PUBLIC_NETWORK, param);
    if (status != LORAMAC_STATUS_OK)
    {
        lorawan_uplink_service_diag.last_mac_status = status;
        return false;
    }

    lorawan_uplink_service_diag.last_mac_status = LORAMAC_STATUS_OK;
    return true;
}

static bool ConfigureAbpSession(void)
{
    MibParam_t param;
    LoRaMacStatus_t status;

    lorawan_uplink_service_diag.abp_session_configure_count++;
    lorawan_uplink_service_diag.activation_mode = ACTIVATION_TYPE_ABP;
    lorawan_uplink_service_diag.abp_dev_addr = BOLUS_LORAWAN_DEV_ADDR;
    lorawan_uplink_service_diag.abp_network_keys_match =
        (memcmp(s_f_nwk_s_int_key,
                s_s_nwk_s_int_key,
                sizeof(s_f_nwk_s_int_key)) == 0);

    /*
     * This repository is built with USE_LRWAN_1_1_X_CRYPTO == 0 and
     * LoRaWAN 1.0.3. In that mode LoRaMAC exposes one MIB_NWK_S_KEY.
     * Reject a 1.1-style session with different F/S network keys instead of
     * silently configuring an invalid session.
     */
    if (!lorawan_uplink_service_diag.abp_network_keys_match)
    {
        lorawan_uplink_service_diag.last_mac_status = LORAMAC_STATUS_PARAMETER_INVALID;
        lorawan_uplink_service_diag.abp_session_configure_failure_count++;
        return false;
    }

    memset(&param, 0, sizeof(param));
    param.AbpLrWanVersion.Value = LORAWAN_ABP_LRWAN_VERSION_V103;
    status = SetMib(MIB_ABP_LORAWAN_VERSION, param);
    if (status != LORAMAC_STATUS_OK)
    {
        lorawan_uplink_service_diag.last_mac_status = status;
        lorawan_uplink_service_diag.abp_session_configure_failure_count++;
        return false;
    }

    memset(&param, 0, sizeof(param));
    param.DevAddr = BOLUS_LORAWAN_DEV_ADDR;
    status = SetMib(MIB_DEV_ADDR, param);
    if (status != LORAMAC_STATUS_OK)
    {
        lorawan_uplink_service_diag.last_mac_status = status;
        lorawan_uplink_service_diag.abp_session_configure_failure_count++;
        return false;
    }

    memset(&param, 0, sizeof(param));
    param.NwkSKey = s_f_nwk_s_int_key;
    status = SetMib(MIB_NWK_S_KEY, param);
    if (status != LORAMAC_STATUS_OK)
    {
        lorawan_uplink_service_diag.last_mac_status = status;
        lorawan_uplink_service_diag.abp_session_configure_failure_count++;
        return false;
    }

    memset(&param, 0, sizeof(param));
    param.AppSKey = s_app_s_key;
    status = SetMib(MIB_APP_S_KEY, param);
    if (status != LORAMAC_STATUS_OK)
    {
        lorawan_uplink_service_diag.last_mac_status = status;
        lorawan_uplink_service_diag.abp_session_configure_failure_count++;
        return false;
    }

    lorawan_uplink_service_diag.abp_session_configured = true;
    lorawan_uplink_service_diag.last_mac_status = LORAMAC_STATUS_OK;
    return true;
}

static bool ActivateAbpSession(void)
{
    MibParam_t param;
    LoRaMacStatus_t status;

    memset(&param, 0, sizeof(param));
    param.NetworkActivation = ACTIVATION_TYPE_ABP;
    status = SetMib(MIB_NETWORK_ACTIVATION, param);
    lorawan_uplink_service_diag.last_mac_status = status;
    if (status != LORAMAC_STATUS_OK)
    {
        lorawan_uplink_service_diag.abp_session_configure_failure_count++;
        return false;
    }

    s_joined = true;
    lorawan_uplink_service_diag.joined = true;
    lorawan_uplink_service_diag.join_in_flight = false;
    lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_JOINED_IDLE;
    s_next_action_tick_ms = HAL_GetTick();
    lorawan_uplink_service_diag.next_action_tick_ms = s_next_action_tick_ms;
    (void)FaultManager_ClearFault(BOLUS_FAULT_RF_COMM);
    return true;
}

static void TrySendControlResponse(uint32_t now_ms)
{
    McpsReq_t request;
    LoRaMacStatus_t status;

    if (!s_control_response_pending || s_tx_in_flight || !s_joined ||
        (s_control_response_size == 0U))
    {
        return;
    }

    memset(&request, 0, sizeof(request));
    request.Type = MCPS_UNCONFIRMED;
    request.Req.Unconfirmed.fPort = BOLUS_LORAWAN_CONTROL_UPLINK_PORT;
    request.Req.Unconfirmed.fBuffer = s_control_response;
    request.Req.Unconfirmed.fBufferSize = s_control_response_size;
    request.Req.Unconfirmed.Datarate = DR_0;

    status = LoRaMacMcpsRequest(&request, true);
    lorawan_uplink_service_diag.last_mac_status = status;

    if (status == LORAMAC_STATUS_OK)
    {
        s_control_response_attempts++;
        s_tx_in_flight = true;
        s_tx_kind = LORAWAN_TX_KIND_CONTROL_RESPONSE;
        lorawan_uplink_service_diag.tx_in_flight = true;
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_TX_IN_FLIGHT;
    }
    else if (status == LORAMAC_STATUS_DUTYCYCLE_RESTRICTED)
    {
        s_next_action_tick_ms = now_ms + request.ReqReturn.DutyCycleWaitTime;
        lorawan_uplink_service_diag.next_action_tick_ms = s_next_action_tick_ms;
        lorawan_uplink_service_diag.duty_cycle_defer_count++;
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_RETRY_WAIT;
    }
    else if (status == LORAMAC_STATUS_BUSY)
    {
        s_next_action_tick_ms = now_ms + LORAWAN_UPLINK_BUSY_RETRY_MS;
        lorawan_uplink_service_diag.next_action_tick_ms = s_next_action_tick_ms;
        lorawan_uplink_service_diag.mac_busy_defer_count++;
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_RETRY_WAIT;
    }
    else if (status == LORAMAC_STATUS_NO_NETWORK_JOINED)
    {
        MarkAbpSessionLost(now_ms);
    }
    else
    {
        lorawan_uplink_service_diag.downlink_response_tx_failure_count++;

        if (s_control_response_attempts < s_max_tx_attempts)
        {
            s_next_action_tick_ms = now_ms + s_retry_delay_ms;
            lorawan_uplink_service_diag.next_action_tick_ms = s_next_action_tick_ms;
            lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_RETRY_WAIT;
        }
        else
        {
            lorawan_uplink_service_diag.downlink_response_drop_count++;
            s_control_response_pending = false;
            s_control_response_size = 0U;
            s_control_response_attempts = 0U;
            memset(s_control_response, 0, sizeof(s_control_response));
            FaultManager_Raise(BOLUS_FAULT_RF_COMM);
            s_next_action_tick_ms = now_ms;
            lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_JOINED_IDLE;
        }
    }
}

static void TrySendHead(uint32_t now_ms)
{
    lorawan_uplink_queue_entry_t *entry = QueueHead();
    McpsReq_t request;
    LoRaMacStatus_t status;

    if ((entry == NULL) || s_tx_in_flight || !s_joined)
    {
        return;
    }

    memset(&request, 0, sizeof(request));

#if (BOLUS_LORAWAN_CONFIRMED_UPLINK != 0)
    request.Type = MCPS_CONFIRMED;
    request.Req.Confirmed.fPort = BOLUS_LORAWAN_APP_PORT;
    request.Req.Confirmed.fBuffer = entry->payload;
    request.Req.Confirmed.fBufferSize = entry->size;
    request.Req.Confirmed.Datarate = DR_0;
    request.Req.Confirmed.NbTrials = BOLUS_LORAWAN_CONFIRMED_TRIALS;
#else
    request.Type = MCPS_UNCONFIRMED;
    request.Req.Unconfirmed.fPort = BOLUS_LORAWAN_APP_PORT;
    request.Req.Unconfirmed.fBuffer = entry->payload;
    request.Req.Unconfirmed.fBufferSize = entry->size;
    request.Req.Unconfirmed.Datarate = DR_0;
#endif

    status = LoRaMacMcpsRequest(&request, true);
    lorawan_uplink_service_diag.last_mac_status = status;

    if (status == LORAMAC_STATUS_OK)
    {
        entry->attempts++;
        s_tx_in_flight = true;
        s_tx_kind = LORAWAN_TX_KIND_TELEMETRY;
        lorawan_uplink_service_diag.tx_in_flight = true;
        lorawan_uplink_service_diag.tx_request_count++;
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_TX_IN_FLIGHT;
    }
    else if (status == LORAMAC_STATUS_DUTYCYCLE_RESTRICTED)
    {
        s_next_action_tick_ms = now_ms + request.ReqReturn.DutyCycleWaitTime;
        lorawan_uplink_service_diag.next_action_tick_ms = s_next_action_tick_ms;
        lorawan_uplink_service_diag.duty_cycle_defer_count++;
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_RETRY_WAIT;
    }
    else if (status == LORAMAC_STATUS_BUSY)
    {
        s_next_action_tick_ms = now_ms + LORAWAN_UPLINK_BUSY_RETRY_MS;
        lorawan_uplink_service_diag.next_action_tick_ms = s_next_action_tick_ms;
        lorawan_uplink_service_diag.mac_busy_defer_count++;
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_RETRY_WAIT;
    }
    else if (status == LORAMAC_STATUS_NO_NETWORK_JOINED)
    {
        MarkAbpSessionLost(now_ms);
    }
    else
    {
        lorawan_uplink_service_diag.tx_failure_count++;

        if (entry->attempts < s_max_tx_attempts)
        {
            lorawan_uplink_service_diag.tx_retry_count++;
            s_next_action_tick_ms = now_ms + s_retry_delay_ms;
            lorawan_uplink_service_diag.next_action_tick_ms = s_next_action_tick_ms;
            lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_RETRY_WAIT;
        }
        else
        {
            lorawan_uplink_service_diag.tx_drop_count++;
            FaultManager_Raise(BOLUS_FAULT_RF_COMM);
            QueuePop();
            s_next_action_tick_ms = now_ms;
            lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_JOINED_IDLE;
        }
    }
}

lorawan_uplink_status_t LoRaWanUplinkService_Init(
    bolus_runtime_config_t *config)
{
    LoRaMacStatus_t mac_status;

    if ((config == NULL) || !BolusRuntimeConfig_Validate(config))
    {
        return LORAWAN_UPLINK_ERROR_CONFIG;
    }

    memset(s_queue, 0, sizeof(s_queue));
    memset(&lorawan_uplink_service_diag, 0, sizeof(lorawan_uplink_service_diag));
    memset(s_control_response, 0, sizeof(s_control_response));
    s_initialized = false;
    s_queue_head = 0U;
    s_queue_tail = 0U;
    s_queue_count = 0U;
    s_control_response_pending = false;
    s_control_response_size = 0U;
    s_control_response_attempts = 0U;
    s_joined = false;
    s_tx_in_flight = false;
    s_tx_kind = LORAWAN_TX_KIND_NONE;
    s_next_action_tick_ms = HAL_GetTick();
    s_retry_delay_ms = config->radio.retry_delay_ms;
    s_max_tx_attempts = config->radio.max_tx_attempts;

    lorawan_uplink_service_diag.credentials_provisioned =
        (BOLUS_LORAWAN_CREDENTIALS_PROVISIONED != 0);
    lorawan_uplink_service_diag.activation_mode = ACTIVATION_TYPE_ABP;
    lorawan_uplink_service_diag.abp_dev_addr = BOLUS_LORAWAN_DEV_ADDR;
    lorawan_uplink_service_diag.queue_capacity = BOLUS_LORAWAN_QUEUE_DEPTH;
    lorawan_uplink_service_diag.app_port = BOLUS_LORAWAN_APP_PORT;

    if (!DownlinkManagementService_Init(config))
    {
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_ERROR;
        FaultManager_Raise(BOLUS_FAULT_CONFIG_INVALID);
        return LORAWAN_UPLINK_ERROR_CONFIG;
    }

    memset(&s_mac_primitives, 0, sizeof(s_mac_primitives));
    s_mac_primitives.MacMcpsConfirm = MacMcpsConfirm;
    s_mac_primitives.MacMcpsIndication = MacMcpsIndication;
    s_mac_primitives.MacMlmeConfirm = MacMlmeConfirm;
    s_mac_primitives.MacMlmeIndication = MacMlmeIndication;

    memset(&s_mac_callbacks, 0, sizeof(s_mac_callbacks));
    s_mac_callbacks.GetBatteryLevel = MacGetBatteryLevel;
    s_mac_callbacks.GetTemperatureLevel = MacGetTemperatureLevel;
    s_mac_callbacks.GetUniqueId = MacGetUniqueId;
    s_mac_callbacks.NvmDataChange = MacNvmDataChange;
    s_mac_callbacks.MacProcessNotify = MacProcessNotify;

    mac_status = LoRaMacInitialization(
        &s_mac_primitives,
        &s_mac_callbacks,
        LORAMAC_REGION_EU868);
    lorawan_uplink_service_diag.last_mac_status = mac_status;

    if (mac_status != LORAMAC_STATUS_OK)
    {
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_ERROR;
        FaultManager_Raise(BOLUS_FAULT_RF_COMM);
        return LORAWAN_UPLINK_ERROR_MAC_INIT;
    }

    if (!ConfigureMacPolicy())
    {
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_ERROR;
        FaultManager_Raise(BOLUS_FAULT_RF_COMM);
        return LORAWAN_UPLINK_ERROR_MIB;
    }

    if (lorawan_uplink_service_diag.credentials_provisioned &&
        !ConfigureAbpSession())
    {
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_ERROR;
        FaultManager_Raise(BOLUS_FAULT_RF_COMM);
        return LORAWAN_UPLINK_ERROR_MIB;
    }

    mac_status = LoRaMacStart();
    lorawan_uplink_service_diag.last_mac_status = mac_status;
    if (mac_status != LORAMAC_STATUS_OK)
    {
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_ERROR;
        FaultManager_Raise(BOLUS_FAULT_RF_COMM);
        return LORAWAN_UPLINK_ERROR_MAC_START;
    }

    if (lorawan_uplink_service_diag.credentials_provisioned &&
        !ActivateAbpSession())
    {
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_ERROR;
        FaultManager_Raise(BOLUS_FAULT_RF_COMM);
        return LORAWAN_UPLINK_ERROR_MIB;
    }

    s_initialized = true;
    lorawan_uplink_service_diag.initialized = true;
    lorawan_uplink_service_diag.next_action_tick_ms = s_next_action_tick_ms;

    if (!lorawan_uplink_service_diag.credentials_provisioned)
    {
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_WAIT_CREDENTIALS;
    }

    return LORAWAN_UPLINK_OK;
}

lorawan_uplink_status_t LoRaWanUplinkService_Submit(
    const uint8_t *payload,
    uint8_t size,
    uint16_t sequence)
{
    lorawan_uplink_queue_entry_t *entry;

    if ((payload == NULL) || (size == 0U) ||
        (size > BOLUS_LORAWAN_MAX_APP_PAYLOAD))
    {
        return LORAWAN_UPLINK_ERROR_PARAM;
    }

    if (!s_initialized)
    {
        return LORAWAN_UPLINK_ERROR_NOT_READY;
    }

    if (s_queue_count >= BOLUS_LORAWAN_QUEUE_DEPTH)
    {
        lorawan_uplink_service_diag.queue_full_count++;
        return LORAWAN_UPLINK_ERROR_QUEUE_FULL;
    }

    entry = &s_queue[s_queue_tail];
    memset(entry, 0, sizeof(*entry));
    memcpy(entry->payload, payload, size);
    entry->size = size;
    entry->sequence = sequence;
    entry->valid = true;

    s_queue_tail = (uint8_t)((s_queue_tail + 1U) % BOLUS_LORAWAN_QUEUE_DEPTH);
    s_queue_count++;

    lorawan_uplink_service_diag.submit_count++;
    lorawan_uplink_service_diag.queue_count = s_queue_count;
    lorawan_uplink_service_diag.last_sequence_submitted = sequence;

    return LORAWAN_UPLINK_OK;
}

void LoRaWanUplinkService_Process(uint32_t now_ms)
{
    if (!s_initialized)
    {
        return;
    }

    RFM95W_Board_ProcessIrqs();
    LoRaMacProcess();
    lorawan_uplink_service_diag.mac_process_pending = false;

    if (!lorawan_uplink_service_diag.credentials_provisioned)
    {
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_WAIT_CREDENTIALS;
        return;
    }

    if (!s_joined || !lorawan_uplink_service_diag.abp_session_configured)
    {
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_ERROR;
        return;
    }

    if (!TimeReached(now_ms, s_next_action_tick_ms))
    {
        return;
    }

    if (!s_tx_in_flight && s_control_response_pending)
    {
        TrySendControlResponse(now_ms);
        return;
    }

    if (!s_tx_in_flight && (s_queue_count > 0U))
    {
        TrySendHead(now_ms);
    }
    else if (!s_tx_in_flight)
    {
        lorawan_uplink_service_diag.state = LORAWAN_UPLINK_STATE_JOINED_IDLE;
    }
}

bool LoRaWanUplinkService_IsReady(void)
{
    return s_initialized;
}

bool LoRaWanUplinkService_CanAccept(void)
{
    return (s_initialized && (s_queue_count < BOLUS_LORAWAN_QUEUE_DEPTH));
}

bool LoRaWanUplinkService_IsJoined(void)
{
    return (s_initialized && s_joined);
}
