#ifndef TELEMETRY_DATA_H
#define TELEMETRY_DATA_H

#include <stdbool.h>
#include <stdint.h>

/*
 * Internal telemetry snapshots.
 *
 * These are application data models, not on-air layouts. The codec explicitly
 * quantizes and serializes fields; never memcpy these structs to the radio.
 */
typedef struct
{
    uint16_t sequence;
    uint16_t config_version;

    bool temperature_valid;
    int32_t temperature_current_mdeg_c;
    int32_t temperature_min_mdeg_c;
    int32_t temperature_max_mdeg_c;
    int32_t max_negative_excursion_mdeg_c;

    bool motion_valid;
    uint16_t motion_event_count;
    uint16_t contraction_candidate_count;
    uint16_t rotation_candidate_count;

    bool inter_event_interval_valid;
    uint16_t inter_event_interval_mean_s;
    uint32_t inter_event_interval_variance_s2;

    uint16_t rms_dynamic_accel_mg;
    uint16_t peak_dynamic_accel_mg;

    uint32_t combined_event_flags;

    uint16_t battery_mv;
    uint8_t battery_percent;

    bool event_record_overflow;
    bool fault_present;
    bool health_degraded;
    bool health_critical;
} bolus_telemetry_summary_v1_t;

/*
 * Episode-aware V2 summary prepared for the new Event Episode architecture.
 * It keeps the most useful 15-minute temperature, pulse-timing and MPU burst
 * features while avoiding raw sensor waveforms.
 */
typedef struct
{
    uint16_t sequence;
    uint16_t config_version;

    bool temperature_valid;
    int32_t temperature_current_mdeg_c;
    int32_t temperature_min_mdeg_c;
    int32_t temperature_max_mdeg_c;
    int32_t max_negative_excursion_mdeg_c;

    bool motion_valid;
    uint16_t episode_count;
    uint16_t accepted_pulse_count;
    uint16_t suppressed_pulse_count;
    uint16_t max_pulses_per_episode;

    bool inter_pulse_interval_valid;
    uint16_t inter_pulse_interval_mean_s;
    uint32_t inter_pulse_interval_variance_s2;

    bool mpu_valid;
    uint16_t mpu_burst_count;
    uint16_t rms_dynamic_accel_mg;
    uint16_t peak_dynamic_accel_mg;
    uint16_t rms_angular_velocity_dps;
    uint16_t peak_angular_velocity_dps;
    uint32_t total_angular_motion_cdeg;
    uint16_t max_orientation_change_cdeg;

    /* Reserved for EventProcessor/classifier integration. */
    uint16_t contraction_candidate_count;
    uint16_t rotation_candidate_count;
    uint32_t combined_event_flags;

    uint16_t battery_mv;
    uint8_t battery_percent;

    bool fault_present;
    bool health_degraded;
    bool health_critical;

    /* Explicitly marks data generated by the current unvalidated staging path. */
    bool staging_untested;
} bolus_telemetry_summary_v2_t;

/*
 * Telemetry V2.1 extends, but does not alter, the frozen V2 application model.
 * The BMA456 fields are a native Step Counter reading and one XYZ acceleration
 * snapshot. They must never be populated from the MPU6050 burst path.
 */
typedef struct
{
    bolus_telemetry_summary_v2_t v2;

    uint32_t bma_step_count;
    int16_t bma_accel_x_mg;
    int16_t bma_accel_y_mg;
    int16_t bma_accel_z_mg;
} bolus_telemetry_summary_v2_1_t;

/*
 * Telemetry V2.2 keeps the proven V2.1 internal snapshot so legacy V2/V2.1
 * encoders remain available. Its wire encoder deliberately omits the derived
 * battery percentage and the currently unconnected staging classifier fields.
 */
typedef bolus_telemetry_summary_v2_1_t bolus_telemetry_summary_v2_2_t;

typedef struct
{
    uint16_t start_offset_s;
    uint16_t duration_s;
    uint8_t pulse_count;
    uint8_t mean_inter_pulse_interval_s;
    int16_t temperature_delta_centi_c;
    uint16_t rms_dynamic_accel_mg;
    uint16_t peak_dynamic_accel_mg;
    uint16_t peak_angular_velocity_dps;
    uint16_t orientation_change_cdeg;
    uint8_t flags;
} bolus_event_digest_t;

#define BOLUS_EVENT_DIGEST_FLAG_MOTION          (1U << 0)
#define BOLUS_EVENT_DIGEST_FLAG_TEMP_HIGH       (1U << 1)
#define BOLUS_EVENT_DIGEST_FLAG_TEMP_LOW        (1U << 2)
#define BOLUS_EVENT_DIGEST_FLAG_MPU_USED        (1U << 3)
#define BOLUS_EVENT_DIGEST_FLAG_MPU_SKIPPED     (1U << 4)
#define BOLUS_EVENT_DIGEST_FLAG_TEMP_VALID      (1U << 5)
#define BOLUS_EVENT_DIGEST_FLAG_MPU_FAILED      (1U << 6)
#define BOLUS_EVENT_DIGEST_FLAG_CARRY           (1U << 7)

#endif /* TELEMETRY_DATA_H */
